### ISSUE TITLE
doesn't work with current django 1.6, likely not with 1.5

### ISSUE THREAD

**Issue by henning** [seantis/seantis-questionnaire#20]
When running the syncdb command from the install instructions, I get:

...
ImportError: No module named markup

Seems to come from the django.contrib.markup import - it's deprecated as of 1.5:
https://groups.google.com/forum/#!topic/django-users/iwfuDFFAltI

There seems to be an alternative, but that requires adjustments:

http://stackoverflow.com/questions/20055603/how-can-i-satisfy-a-django-contrib-markup-templatetags-markup-import-restructure

**Comment by msom** [comment]
Should now work with Django 1.8
