### ISSUE TITLE
Question Footer not rendering as textile

### ISSUE THREAD

**Issue by h0h0h0** [seantis/seantis-questionnaire#24]
Hello,

I added some textile markup to the question footer but it's not rendering as textile. 

I see this in the questionset.html view  but can't really see where it's rendering as textile.

```
            {% if question.footer %}
                <div class="question-footer">
                    {{ question.footer }}
                    <div class="clearfix"></div>
                </div>
```

**Comment by msom** [comment]
Fixed with 7dbbbf1917c1546a4085067df7a3d6a13bff0a1f
