### ISSUE TITLE
django-compatpyyaml

### ISSUE THREAD

**Issue by nordbit** [seantis/seantis-questionnaire#49]
error: Could not find suitable distribution for Requirement.parse('django-compatpyyaml')

**Comment by href** [comment]
Fixed: https://github.com/seantis/seantis-questionnaire/commit/26c7084af087c5a5923b55c61b7d8e624e6754cd

Note that seantis questionnaire is no longer worked on. Use ed-questionnaire for new projects:
https://github.com/eldest-daughter/ed-questionnaire
