### ISSUE TITLE
This project needs a maintainer

### ISSUE THREAD

**Issue by bashu** [seantis/seantis-questionnaire#51]
Hi, 

This repository seems to lack maintenance, I propose myself as a new maintainer. Could 
you give me the right to push in your repository or just transfer it on my account in github? 

Thank you.

**Comment by href** [comment]
Unfortunately, this project is in use by one of our clients and we therefore are unable to transfer ownership. However, there's a fork that was created a few years back that added some things and fixed some bugs: https://github.com/eldest-daughter/ed-questionnaire

This fork is no longer under maintenance either, but I would consider it a better starting point for creating your own fork.

**Comment by bashu** [comment]
@href that's sad, cuz this way established user base will be lost..

**Comment by bashu** [comment]
and you don't accept RP either?

**Comment by href** [comment]
I'm afraid not. But since there haven't been any new issues and/or PRs in 4 years I would assume that people have moved on.
